# src/main/resources/application.yml
spring:
  security:
    oauth2:
      client:
        registration:
          auth0:
            client-id: n1Ps6zZxgqXJvXMIgtp9QjxJeXUCSrqk
            client-secret: aSVrpohZJC3ir9T_JoGXF_cJB5Jn0q6O7804ov29I8eSpikf_F_3fC-GSwstyxQT
            scope:
              - openid
              - profile
              - email
        provider:
          auth0:
            # trailing slash is important!
            issuer-uri: https://dev-3taelgkw.us.auth0.com/
